FROM php:7-apache
RUN apt-get update
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libmcrypt-dev zlib1g-dev libzip-dev libcurl4-openssl-dev nano
RUN docker-php-ext-install -j$(nproc) gd curl mysqli pdo_mysql zip
RUN pecl install mcrypt-1.0.4
RUN docker-php-ext-enable mcrypt
